### ISSUE TITLE
It's failed to run the Keycloak Admin CLI step

### ISSUE THREAD

**Issue by peter279k** [carlosthe19916/keycloak-action#10]
As title, when using the following steps in the GitHub  workflow it will present the error message:

```yml
.....
    - name: Init Keycloak
        run: |
          docker run -d --name keycloak -p 8080:8080 \
          -e KEYCLOAK_ADMIN=admin \
          -e KEYCLOAK_ADMIN_PASSWORD=admin \
          quay.io/keycloak/keycloak:latest start-dev

      - name: Keycloak Admin CLI
        uses: carlosthe19916/keycloak-action@0.6
        with:
          version: latest
          server: http://localhost:8080
          username: admin
          password: admin
          kcadm: |
            config credentials --server http://localhost:8080 --realm master --user admin --password admin
            update realms/master -s sslRequired=NONE --server http://localhost:8080
....
```

The error message is as follows:

```
Waiting for http://localhost:8080
Error: LinkageError occurred while loading main class org.keycloak.client.admin.cli.KcAdmMain
	java.lang.UnsupportedClassVersionError: org/keycloak/client/admin/cli/KcAdmMain has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

I suspect the Java version is not consistency and it should upgrade or change the Java runtime version.

I also fork this repository and run the GitHub workflow to verify this issue.

My GitHub action log is available [here](https://github.com/peter279k/keycloak-action/actions/runs/12309213081/job/34355871066).
