### ISSUE TITLE
Upgrading to the latest stable version

### ISSUE THREAD

**Issue by peter279k** [carlosthe19916/keycloak-action#3]
According to the `README.md`, it seems that it uses the `quay.io/keycloak/keycloak:12.0.1`. But the current latest released is `25.0.2`.

Is there any plan to upgrade the `Keycloak` to the current latest released version?

**Comment by carlosthe19916** [comment]
@peter279k I have just updated the action to allow the Keycloak version client to be customizable. The code in master branch should allow this:
```yaml
steps:
- uses: actions/checkout@v2
- name: Keycloak Admin CLI
  uses: carlosthe19916/keycloak-action@master
  with:
## Set Keycloak version here
    version: latest
    server: http://keycloak:8080/auth
    username: admin
    password: admin
    kcadm: create realms -f openubl-realm.json
```

Here is an example:
https://github.com/carlosthe19916/keycloak-action/blob/master/.github/workflows/ci.yaml

I won't release it until 2 weeks from now. I need to test the action against the latest version of keycloak and I won't be in my laptop for 2 weeks

**Comment by peter279k** [comment]
@carlosthe19916, thanks for your reply. I'll check that with the master branch in my project :).

**Comment by peter279k** [comment]
Unfortunately, it seems that the Keycloak server cannot be run and I always get the `Max attempts reached` message.

Here is [my Workflow log](https://github.com/peter279k/fhir-data-generator/actions/runs/10380721781/job/28741024604) and [workflow YAML file](https://github.com/peter279k/fhir-data-generator/blob/f715215483cce432a992112b96ab9a55d1752f58/.github/workflows/test-suite.yml).

**Comment by carlosthe19916** [comment]
You are using a version of keycloak that require a command to start the server. So unfortunately we cannot use the image: quay.io/keycloak/keycloak:25.0.2 on the "services" section of GH actions as we cannot pass a command. On the other hand starting Docker with a plain docker command will make it start with a separate network and the action will not be able to reach it.... This is something I wanted to test... replying from my phone so I don't have a computer to check it now but I'll do it on the weekend.

**Comment by carlosthe19916** [comment]
This one works 
‚‚‚
strategy:
      matrix:
        version: ["12.0.2", "19.0.3-legacy"]
      fail-fast: false
    services:
      keycloak:
        image: quay.io/keycloak/keycloak:${{ matrix.version }}

But I need to find a way to test higher versions of keycloak

**Comment by peter279k** [comment]
Thanks for your reply and I appreciate your help!

At this moment, I use the Docker directly without using the container service in the GitHub action.

You can check [this](https://github.com/peter279k/fhir-data-generator/blob/master/.github/workflows/test-suite.yml#L32) at this weekend :).

**Comment by carlosthe19916** [comment]
@peter279k I have just released a new version of this action

I added tests to this repository to verify it works with multiple versions of Keycloak. You can check the gh workflow this repository uses for testing here https://github.com/carlosthe19916/keycloak-action/blob/master/.github/workflows/ci.yaml

Long story short you can do something like:
```yaml
 steps:
      - name: Init Keycloak
        run: |
          docker run -d --name keycloak -p 8080:8080 \
          -e KEYCLOAK_ADMIN=admin \
          -e KEYCLOAK_ADMIN_PASSWORD=password \
          quay.io/keycloak/keycloak:latest start-dev
      - name: Keycloak Admin CLI
        uses: carlosthe19916/keycloak-action@0.6
        with:
          version: latest
          server: http://localhost:8080
          username: admin
          password: password
          kcadm: get realms
```
